{
    "description": "A scalable method for finding frequent patterns within large datasets.", 
    "license": {
        "text": "CognitiveScale", 
        "type": "Apache"
    }, 
    "tags": [
        {
            "value": "skill.deployment.cloud", 
            "label": "Cloud"
        }, 
        {
            "value": "skill.machine_learning_style.deep_learning", 
            "label": "Deep Learning"
        }, 
        {
            "value": "skill.machine_learning_style.unsupervisedlearning", 
            "label": "UnSupervised Learning"
        }, 
        {
            "value": "skill.service_providers.algorithmia", 
            "label": "Algorithmia"
        }, 
        {
            "value": "skill.status.install", 
            "label": "Install"
        }
    ], 
    "price": {
        "value": "00", 
        "unit": "CCU"
    }, 
    "title": "Product Affinity Analysis", 
    "asset": {
        "description": "A scalable method for finding frequent patterns within large datasets.", 
        "name": "cortex/product_affinity_analysis", 
        "title": "Product Affinity Analysis"
    }, 
    "tutorials": [
        {
            "videoLink": "http://video.avi", 
            "description": "Tutorial Description", 
            "title": "Tutorial Title"
        }
    ], 
    "icon": "http://icon.png"
}